//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgramClient.HelloWorldService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://helloworld.org.rsi/", ConfigurationName="HelloWorldService.HelloWorld")]
    public interface HelloWorld {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://helloworld.org.rsi/HelloWorld/getHelloWorldAsStringRequest", ReplyAction="http://helloworld.org.rsi/HelloWorld/getHelloWorldAsStringResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ProgramClient.HelloWorldService.getHelloWorldAsStringResponse getHelloWorldAsString(ProgramClient.HelloWorldService.getHelloWorldAsStringRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://helloworld.org.rsi/HelloWorld/getHelloWorldAsStringRequest", ReplyAction="http://helloworld.org.rsi/HelloWorld/getHelloWorldAsStringResponse")]
        System.Threading.Tasks.Task<ProgramClient.HelloWorldService.getHelloWorldAsStringResponse> getHelloWorldAsStringAsync(ProgramClient.HelloWorldService.getHelloWorldAsStringRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://helloworld.org.rsi/HelloWorld/getProductsRequest", ReplyAction="http://helloworld.org.rsi/HelloWorld/getProductsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ProgramClient.HelloWorldService.getProductsResponse getProducts(ProgramClient.HelloWorldService.getProductsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://helloworld.org.rsi/HelloWorld/getProductsRequest", ReplyAction="http://helloworld.org.rsi/HelloWorld/getProductsResponse")]
        System.Threading.Tasks.Task<ProgramClient.HelloWorldService.getProductsResponse> getProductsAsync(ProgramClient.HelloWorldService.getProductsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getHelloWorldAsString", WrapperNamespace="http://helloworld.org.rsi/", IsWrapped=true)]
    public partial class getHelloWorldAsStringRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://helloworld.org.rsi/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public getHelloWorldAsStringRequest() {
        }
        
        public getHelloWorldAsStringRequest(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getHelloWorldAsStringResponse", WrapperNamespace="http://helloworld.org.rsi/", IsWrapped=true)]
    public partial class getHelloWorldAsStringResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://helloworld.org.rsi/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public getHelloWorldAsStringResponse() {
        }
        
        public getHelloWorldAsStringResponse(string @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://helloworld.org.rsi/")]
    public partial class product : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int cenaField;
        
        private string nazwaField;
        
        private string opisField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int cena {
            get {
                return this.cenaField;
            }
            set {
                this.cenaField = value;
                this.RaisePropertyChanged("cena");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nazwa {
            get {
                return this.nazwaField;
            }
            set {
                this.nazwaField = value;
                this.RaisePropertyChanged("nazwa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string opis {
            get {
                return this.opisField;
            }
            set {
                this.opisField = value;
                this.RaisePropertyChanged("opis");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getProducts", WrapperNamespace="http://helloworld.org.rsi/", IsWrapped=true)]
    public partial class getProductsRequest {
        
        public getProductsRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getProductsResponse", WrapperNamespace="http://helloworld.org.rsi/", IsWrapped=true)]
    public partial class getProductsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://helloworld.org.rsi/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ProgramClient.HelloWorldService.product[] @return;
        
        public getProductsResponse() {
        }
        
        public getProductsResponse(ProgramClient.HelloWorldService.product[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface HelloWorldChannel : ProgramClient.HelloWorldService.HelloWorld, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HelloWorldClient : System.ServiceModel.ClientBase<ProgramClient.HelloWorldService.HelloWorld>, ProgramClient.HelloWorldService.HelloWorld {
        
        public HelloWorldClient() {
        }
        
        public HelloWorldClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HelloWorldClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HelloWorldClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HelloWorldClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProgramClient.HelloWorldService.getHelloWorldAsStringResponse ProgramClient.HelloWorldService.HelloWorld.getHelloWorldAsString(ProgramClient.HelloWorldService.getHelloWorldAsStringRequest request) {
            return base.Channel.getHelloWorldAsString(request);
        }
        
        public string getHelloWorldAsString(string arg0) {
            ProgramClient.HelloWorldService.getHelloWorldAsStringRequest inValue = new ProgramClient.HelloWorldService.getHelloWorldAsStringRequest();
            inValue.arg0 = arg0;
            ProgramClient.HelloWorldService.getHelloWorldAsStringResponse retVal = ((ProgramClient.HelloWorldService.HelloWorld)(this)).getHelloWorldAsString(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProgramClient.HelloWorldService.getHelloWorldAsStringResponse> ProgramClient.HelloWorldService.HelloWorld.getHelloWorldAsStringAsync(ProgramClient.HelloWorldService.getHelloWorldAsStringRequest request) {
            return base.Channel.getHelloWorldAsStringAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProgramClient.HelloWorldService.getHelloWorldAsStringResponse> getHelloWorldAsStringAsync(string arg0) {
            ProgramClient.HelloWorldService.getHelloWorldAsStringRequest inValue = new ProgramClient.HelloWorldService.getHelloWorldAsStringRequest();
            inValue.arg0 = arg0;
            return ((ProgramClient.HelloWorldService.HelloWorld)(this)).getHelloWorldAsStringAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProgramClient.HelloWorldService.getProductsResponse ProgramClient.HelloWorldService.HelloWorld.getProducts(ProgramClient.HelloWorldService.getProductsRequest request) {
            return base.Channel.getProducts(request);
        }
        
        public ProgramClient.HelloWorldService.product[] getProducts() {
            ProgramClient.HelloWorldService.getProductsRequest inValue = new ProgramClient.HelloWorldService.getProductsRequest();
            ProgramClient.HelloWorldService.getProductsResponse retVal = ((ProgramClient.HelloWorldService.HelloWorld)(this)).getProducts(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProgramClient.HelloWorldService.getProductsResponse> ProgramClient.HelloWorldService.HelloWorld.getProductsAsync(ProgramClient.HelloWorldService.getProductsRequest request) {
            return base.Channel.getProductsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProgramClient.HelloWorldService.getProductsResponse> getProductsAsync() {
            ProgramClient.HelloWorldService.getProductsRequest inValue = new ProgramClient.HelloWorldService.getProductsRequest();
            return ((ProgramClient.HelloWorldService.HelloWorld)(this)).getProductsAsync(inValue);
        }
    }
}
